# Generated by Django 5.0.4 on 2024-04-18 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notion',
            options={'verbose_name': 'Заметка', 'verbose_name_plural': 'Заметки'},
        ),
    ]
